# Generated by Django 3.1.4 on 2020-12-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_image_url',
            field=models.URLField(default='', verbose_name='Background Imange URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(default='', verbose_name='Profile Imange URL'),
        ),
    ]
