# Generated by Django 3.1.4 on 2020-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookoverview',
            old_name='sub_category',
            new_name='book_category',
        ),
        migrations.AlterField(
            model_name='content',
            name='main_image_url',
            field=models.URLField(null=True, verbose_name='Content Main Image URL'),
        ),
    ]
