# Generated by Django 3.1.4 on 2020-12-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201216_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.job')),
            ],
            options={
                'db_table': 'content_people',
            },
        ),
        migrations.RemoveField(
            model_name='staff',
            name='content',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffjobs',
            name='job',
        ),
        migrations.RemoveField(
            model_name='staffjobs',
            name='staff',
        ),
        migrations.AddField(
            model_name='people',
            name='profile_image_url',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='PeopleJob',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffJobs',
        ),
        migrations.AddField(
            model_name='contentpeople',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.people'),
        ),
    ]
